# Generated by Django 3.0.8 on 2020-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='center_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='center_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_format',
            field=models.CharField(db_index=True, default='png', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='business_type',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
