# Generated by Django 3.0.8 on 2020-07-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0002_auto_20200715_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='extracted_text_formatted',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='extracted_text_raw',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
