# Generated by Django 3.0.8 on 2020-08-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0003_auto_20200719_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=500)),
                ('external_resource', models.CharField(db_index=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('dt_inserted', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=500, null=True)),
                ('external_resource', models.CharField(db_index=True, max_length=64, null=True)),
                ('file_name', models.CharField(db_index=True, max_length=64)),
                ('mime_type', models.CharField(db_index=True, max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('dt_taken', models.DateTimeField(null=True)),
                ('dt_inserted', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('facets', models.CharField(max_length=1024, null=True)),
                ('extracted_text', models.CharField(max_length=4096, null=True)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockdownsf.Album')),
            ],
        ),
    ]
