# Generated by Django 3.0.8 on 2020-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0005_auto_20200805_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
