# Generated by Django 3.0.8 on 2020-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0006_auto_20200805_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='thumb_url',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='extracted_text',
            field=models.CharField(max_length=16000, null=True),
        ),
    ]
