# Generated by Django 3.0.8 on 2020-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0007_auto_20200805_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='external_id',
            field=models.CharField(db_index=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='external_id',
            field=models.CharField(db_index=True, max_length=500, null=True, unique=True),
        ),
    ]
