# Generated by Django 3.0.8 on 2020-08-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0009_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lockdownsf.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lockdownsf.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lockdownsf.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'owner')},
        ),
    ]
