# Generated by Django 3.0.8 on 2020-08-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0011_auto_20200811_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaitem',
            old_name='extracted_text',
            new_name='extracted_text_display',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='extracted_text_search',
            field=models.CharField(max_length=16000, null=True),
        ),
    ]
