# Generated by Django 3.0.8 on 2020-08-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0012_auto_20200813_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='external_resource',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='external_resource',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='facets',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='thumb_url',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='width',
        ),
    ]
