# Generated by Django 3.0.8 on 2020-08-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0014_auto_20200820_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos_having_gps',
            field=models.IntegerField(default=0),
        ),
    ]
