# Generated by Django 3.0.8 on 2020-08-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0015_album_photos_having_gps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
