# Generated by Django 3.0.8 on 2020-09-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0017_auto_20200830_0104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaItem',
            new_name='Photo',
        ),
    ]
