# Generated by Django 3.0.8 on 2020-09-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0018_auto_20200901_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='andyshirey', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
