# Generated by Django 4.1.1 on 2022-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0019_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='external_id',
            new_name='s3_dir',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('album', 'file_name')},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='external_id',
        ),
    ]
