# Generated by Django 4.1.1 on 2022-09-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0020_rename_external_id_album_s3_dir_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='s3_dir',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockdownsf.album'),
        ),
    ]
