# Generated by Django 4.1.1 on 2022-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdownsf', '0021_alter_album_s3_dir_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='s3_dir',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
